Newbie_Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pacman/", include("pacman.urls")),
]

pacman/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("show_ranking/", views.show_ranking, name="show_ranking"),
    path("start_game/", views.start_game, name="start_game"),
    path("add_ranking/<int:score>/", views.add_ranking, name="add_ranking"),
]

pacman/models.py
from django.db import models

class Ranker(models.Model):
    name = models.CharField(max_length=12)
    score = models.IntegerField()
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'ranker'

pacman/forms.py
from django import forms
from .models import Ranker

class Ranker_form(forms.ModelForm):
    class Meta:
        model = Ranker
        fields = (
            'name',
        )
        widgets = {
            'name' : forms.TextInput(attrs={'style': 'max-width: 300px;'}),
        }
        labels = {
            'name' : '이름 ',
        }

pacman/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Ranker
from .forms import Ranker_form

def index(request):
    messages.info(request, 'Your password has been changed successfully!')
    return render(request, 'pacman/index.html')

def show_ranking(request):
    ranker_list = Ranker.objects.order_by('-score')[:10]
    context = {
        'ranker_list': ranker_list,
    }
    return render(request, 'pacman/ranking.html', context)

def start_game(request):
    scores = Ranker.objects.order_by('-score')[:10] # 게임 시작할 때 10등의 점수 미리 넘겨주기
    if len(scores) >= 10: # 만약 리스트의 길이가 10명이 넘을 때, 10등의 점수를 넘겨줌
        limit_score = Ranker.objects.order_by('-score')[9:10]
        limit_score = limit_score[0].score
    else: # 랭커가 아직 10명이 안찼을 경우, 무조건 랭커로 등록하기 위해 기준 점수를 0점으로 줌
        limit_score = 0
    context = {
        'limit_score': limit_score
    }
    return render(request, 'pacman/game.html', context)

def add_ranking(request, score):
    ranker_list = Ranker.objects.all()
    if request.method == 'POST':
        form = Ranker_form(request.POST)
        if form.is_valid():
            ranker = form.save(commit=False)
            name_list = Ranker.objects.filter(name=request.POST['name'])
            if (len(name_list) > 0) :
                form = Ranker_form()
                context = {'form': form, 'score': score, 'ranker_list': ranker_list}
                return render(request, 'pacman/add_ranking.html', context)
            else:
                ranker.name = request.POST['name']
                ranker.score = score
                ranker.save()
                return redirect('show_ranking')
    else:
        form = Ranker_form()
    context = {'form': form, 'ranker_list': ranker_list}
    return render(request, 'pacman/add_ranking.html', context)

pacman/templates/pacman/add_ranking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Foldit:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/de74b38e3b.js" crossorigin="anonymous"></script>

</head>
<style>

@font-face {
        font-family: pacmanfont;
        src: url("/static/fonts/Pacmanfont.ttf");
    }

body {
    background-color : black;
    color : white;
}

header {
    font-family: 'pacmanfont', cursive;
    font-size: 90px;
    color:yellow;
}

.wrapper {
    margin-top : 120px;
    width : 440px;
    height : 540px;
    margin: auto;
    text-align : center;
}

.info_wrapper {
    margin: 0 auto;
    margin-top : 150px;
    width : 440px;
    height : 30px;
    text-align : right;
}
</style>
<body>
<div class="info_wrapper">
    <i class="fa-solid fa-house" onclick="location.href='{% url 'index' %}'" style="color:white; font-size:20px;"></i>
</div>
<div class="wrapper">
    <header>New Record!</header>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary" id="info-submit">등록</button>
        </form>
</div>
<script>
    var used_names = [
        {% for ranker_list in ranker_list %}
        "{{ ranker_list.name }}",
        {% endfor %}
    ]

    document.querySelector('#id_name').focus();
    document.querySelector('#info-submit').onclick = function(e) {
        var userName = document.getElementById("id_name").value
        if (used_names.includes(userName)) {
            alert("이미 존재하는 닉네임입니다.")
        }
    }
</script>
</body>
</html>

pacman/templates/pacman/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pacman</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Foldit:wght@500&display=swap" rel="stylesheet">
</head>
<style>
    body {
        background-color : black;
        color : white;
        display: flex;
        justify-content: center;
        align-items: center;
        height : 670px;

        margin: 0;
    }

    header {
        font-family: 'pacmanfont', cursive;
        font-size: 100px;
        color: yellow;

    }

    .wrapper {
        margin-top : 160px;
        width : 440px;
        height : 540px;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align : center;
    }

    .btn-jittery {
        margin: 20px; /* 원하는 간격 설정 */
        animation: jittery 3s infinite;
    }

    @keyframes jittery {
        5%, 50% {
            transform: scale(1);
        }
        10% {
            transform: scale(0.9);
        }
        15% {
            transform: scale(1.15);
        }
        20% {
            transform: scale(1.15) rotate(-5deg);
        }
        25% {
            transform: scale(1.15) rotate(5deg);
        }
        30% {
            transform: scale(1.15) rotate(-3deg);
        }
        35% {
            transform: scale(1.15) rotate(2deg);
        }
        40% {
            transform: scale(1.15) rotate(0);
        }
    }

    .centered-button {
        margin: 10px; /* 원하는 간격 설정 */
    }

    .centered-image {
        margin-top : 10px;
        width: 70px;
        height: 70px;
    }
    @font-face {
        font-family: pacmanfont;
        src: url("/static/fonts/Pacmanfont.ttf");
    }
</style>
</head>
<body>
<div class="wrapper">
<header>Pacman</header>

<img src="/static/img/ranking.png" class="centered-image" alt="랭킹 이미지">
<button class="centered-button btn-jittery" onclick="location.href='{% url 'show_ranking' %}'">랭킹 보기</button>

<img src="/static/img/start.png" class="centered-image" alt="게임 시작 이미지">
<button class="centered-button btn-jittery" onclick="location.href='{% url 'start_game' %}'">게임 시작</button>
</div>
</body>
</html>

pacman/templates/pacman/ranking.html
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Ranking</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Foldit:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/de74b38e3b.js" crossorigin="anonymous"></script>
    <script src="{% static 'MQTT/paho-mqtt.js' %}"></script>
    <script src="{% static 'MQTT/paho-mqtt-min.js' %}"></script>
</head>
<style>
    @font-face {
        font-family: pacmanfont;
        src: url("/static/fonts/Pacmanfont.ttf");
    }

body {
    background-color : black;
    color : white;
}

header {
    font-family: 'pacmanfont', cursive;
    margin-top : 20px;
    width : 440px;
    font-size: 90px;
    color: yellow;
    text-align : center;
    display: flex;
        justify-content: center;
        align-items: center;
}

.wrapper {
    width : 440px;
    height : 540px;
    margin: auto;
    margin-top : 120px;
    text-align : center;
}

.info_wrapper {
    height : 30px;
    text-align : right;
}

table {
    width : 450px;
}

</style>
<body>
<div class="wrapper">
    <div class="info_wrapper">
        <i class="fa-solid fa-house" onclick="location.href='{% url 'index' %}'" style="color:white; font-size:25px;"></i>
    </div>
        <header>Ranking</header>
        <table>
            <thead>
              <tr>
                  <th style="width:10%;">순위</th>
                  <th style="width:70%;">이름</th>
                  <th style="width:20%;">점수</th>
              </tr>
            </thead>

            <tbody>
            {% for ranker in ranker_list %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ ranker.name }}</td>
                  <td>{{ ranker.score }}</td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
<script>
    const roomName = 'pacman_constrol';

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/pacman/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) { // 메시지를 받으면 이 메시지의 next_position을 다음 경로로 삼는다
        const data = JSON.parse(e.data);
        console.log("pacman's next position : ", data.position)
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    chatSocket.onopen = () => {
        chatSocket.send(JSON.stringify({
                'message': 'socket opened',
                'current_position' : '',
                'next_position' : ''
        }));
    }

    chatSocket.send(JSON.stringify({ // 키보드 입력이 들어오면 현재의 위치를 보낸다
                'message': 'give me next position',
                'current_position' : '100',
                'next_position' : ''
            }));
</script>

</body>
</html>